apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: webapp-ns
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: 227480286570.dkr.ecr.us-east-1.amazonaws.com/color-app:latest
    env:
      - name: DBHOST
        value: "10.244.0.6"
      - name: DBPORT
        value: "3306"
      - name: DATABASE
        value: "employees"
      - name: DBPWD
        value: "dbpassword"
    ports:
    - containerPort: 8080