apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-replicaset
  namespace: webapp-ns
  labels:
    app: webapp
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 227480286570.dkr.ecr.us-east-1.amazonaws.com/color-app:latest
        env:
        - name: DBHOST
          value: "mysql-db.sql-ns.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "dbpassword"
        ports:
        - containerPort: 8080